version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_ecommerce
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend_network

  maildev:
    image: maildev/maildev
    container_name: maildev_container
    env_file:
      - .env
    ports:
      - '${MAILDEV_HTTP_PORT}:1080'
      - '${MAILDEV_SMTP_PORT}:1025'
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
